class_name AdventureScale
extends RefCounted

# One exploration human is the stable unit for world presentation. Props derive
# from this value so a camera change cannot silently turn architecture into toys.
const HUMAN_HEIGHT: float = 142.0

const PLAYER_DISPLAY_BOX := Vector2(116.0, HUMAN_HEIGHT)
const NPC_DISPLAY_BOX := Vector2(104.0, HUMAN_HEIGHT * 0.96)

const SIGN_HEIGHT_IN_HUMANS: float = 0.72
const LANTERN_HEIGHT_IN_HUMANS: float = 1.72
const TREE_HEIGHT_IN_HUMANS: float = 2.10
const HOUSE_HEIGHT_IN_HUMANS: float = 3.65
const COTTAGE_HEIGHT_IN_HUMANS: float = 2.72
const MARKET_HEIGHT_IN_HUMANS: float = 1.92
const CIVIC_HALL_HEIGHT_IN_HUMANS: float = 4.95
const HOMESTEAD_HEIGHT_IN_HUMANS: float = 5.15
const WHEAT_HEIGHT_IN_HUMANS: float = 2.65
const SHRUB_HEIGHT_IN_HUMANS: float = 0.78
const RIVER_CROSSING_HEIGHT_IN_HUMANS: float = 5.3

const SIGN_DISPLAY_BOX := Vector2(96.0, HUMAN_HEIGHT * SIGN_HEIGHT_IN_HUMANS)
const LANTERN_DISPLAY_BOX := Vector2(152.0, HUMAN_HEIGHT * LANTERN_HEIGHT_IN_HUMANS)
const TREE_DISPLAY_BOX := Vector2(290.0, HUMAN_HEIGHT * TREE_HEIGHT_IN_HUMANS)
const HOUSE_DISPLAY_BOX := Vector2(HUMAN_HEIGHT * 3.90, HUMAN_HEIGHT * HOUSE_HEIGHT_IN_HUMANS)
const COTTAGE_DISPLAY_BOX := Vector2(HUMAN_HEIGHT * 3.05, HUMAN_HEIGHT * COTTAGE_HEIGHT_IN_HUMANS)
const MARKET_DISPLAY_BOX := Vector2(HUMAN_HEIGHT * 2.90, HUMAN_HEIGHT * MARKET_HEIGHT_IN_HUMANS)
const CIVIC_HALL_DISPLAY_BOX := Vector2(HUMAN_HEIGHT * 5.05, HUMAN_HEIGHT * CIVIC_HALL_HEIGHT_IN_HUMANS)
const HOMESTEAD_DISPLAY_BOX := Vector2(HUMAN_HEIGHT * 7.1, HUMAN_HEIGHT * HOMESTEAD_HEIGHT_IN_HUMANS)
const WHEAT_DISPLAY_BOX := Vector2(HUMAN_HEIGHT * 6.7, HUMAN_HEIGHT * WHEAT_HEIGHT_IN_HUMANS)
const SHRUB_DISPLAY_BOX := Vector2(HUMAN_HEIGHT * 1.28, HUMAN_HEIGHT * SHRUB_HEIGHT_IN_HUMANS)
const RIVER_CROSSING_DISPLAY_BOX := Vector2(HUMAN_HEIGHT * 3.0, HUMAN_HEIGHT * RIVER_CROSSING_HEIGHT_IN_HUMANS)
const RIVER_STAIR_DISPLAY_BOX := Vector2(200.0, 190.0)
const ROCK_DISPLAY_BOX := Vector2(144.0, 106.0)

const HOUSE_FOOTPRINT := Vector2(HUMAN_HEIGHT * 3.25, HUMAN_HEIGHT * 0.92)
const HOUSE_COLLISION_OFFSET := Vector2(0.0, -HUMAN_HEIGHT * 0.34)
const COTTAGE_FOOTPRINT := Vector2(HUMAN_HEIGHT * 2.34, HUMAN_HEIGHT * 0.72)
const COTTAGE_COLLISION_OFFSET := Vector2(0.0, -HUMAN_HEIGHT * 0.28)
const MARKET_FOOTPRINT := Vector2(HUMAN_HEIGHT * 2.18, HUMAN_HEIGHT * 0.54)
const MARKET_COLLISION_OFFSET := Vector2(0.0, -HUMAN_HEIGHT * 0.20)
const CIVIC_HALL_FOOTPRINT := Vector2(HUMAN_HEIGHT * 4.35, HUMAN_HEIGHT * 1.06)
const CIVIC_HALL_COLLISION_OFFSET := Vector2(0.0, -HUMAN_HEIGHT * 0.38)
const HOMESTEAD_FOOTPRINT := Vector2(HUMAN_HEIGHT * 5.7, HUMAN_HEIGHT * 1.55)
const HOMESTEAD_COLLISION_OFFSET := Vector2(0.0, -HUMAN_HEIGHT * 0.72)
const WHEAT_FOOTPRINT := Vector2(HUMAN_HEIGHT * 5.7, HUMAN_HEIGHT * 1.28)
const WHEAT_COLLISION_OFFSET := Vector2(0.0, -HUMAN_HEIGHT * 0.62)
const SHRUB_COLLISION_RADIUS: float = HUMAN_HEIGHT * 0.12
const TREE_COLLISION_RADIUS: float = HUMAN_HEIGHT * 0.21
const ROCK_COLLISION_RADIUS: float = 24.0
const SIGN_COLLISION_RADIUS: float = 11.0
const LANTERN_COLLISION_RADIUS: float = 17.0

const HOUSE_SOURCE_DISPLAY_HEIGHT: float = 372.0
const HOUSE_ART_SCALE: float = HOUSE_DISPLAY_BOX.y / HOUSE_SOURCE_DISPLAY_HEIGHT
const LANTERN_SOURCE_DISPLAY_HEIGHT: float = 178.0
const LANTERN_ART_SCALE: float = LANTERN_DISPLAY_BOX.y / LANTERN_SOURCE_DISPLAY_HEIGHT
const LANTERN_FLAME_POSITION := Vector2(-19.0, -111.0) * LANTERN_ART_SCALE
const LANTERN_FLAME_SCALE := Vector2.ONE * LANTERN_ART_SCALE

# Zooming out exposes more authored world while the upward focus offset keeps
# the player in the lower third and the now-correct lodge roof inside frame.
const EXPLORATION_CAMERA_ZOOM := Vector2(0.82, 0.82)
const EXPLORATION_CAMERA_OFFSET := Vector2(0.0, -330.0)
